name: Scrape CSFD

on:
  schedule:
    - cron: "0 3 * * 1"   # weekly
  workflow_dispatch: {}    # allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # ⚠️ nic o "cache" tady nechtej

      - name: Install deps (Playwright + Chromium)
        run: |
          npm i
          npx playwright install --with-deps chromium

      - name: Run scraper
        run: node scrape_csfd.mjs

      - name: Commit CSV (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/csfd_ratings.csv
          git commit -m "Update csfd_ratings.csv [skip ci]" || echo "No changes"
          git push
